<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Api\ClienteController;
use App\Http\Controllers\Api\ProfesionalController;
use App\Http\Controllers\Api\ReservaController;
use App\Http\Controllers\Api\ServicioController;
use App\Http\Controllers\Api\ServicioComunController;
use App\Http\Controllers\Api\UbicacionController;
use App\Http\Controllers\Api\ReglaDisponibilidadController;
use App\Http\Controllers\Api\ResenaController;
use App\Http\Controllers\Api\UsuarioController;
use App\Http\Controllers\Api\VideoSesionController;
use App\Http\Controllers\Api\AgendaController;
use App\Http\Controllers\Api\HorarioController;
use App\Http\Controllers\Api\ExcepcionDisponibilidadController;
use App\Http\Controllers\Api\NotificacionController;
use App\Http\Controllers\Api\DisponibilidadController;
use App\Http\Controllers\Api\PagoController;
use App\Http\Controllers\Api\PaqueteServicioController;
use App\Http\Controllers\Api\PaqueteCompradoController;
use App\Http\Controllers\Api\CicloController;
use App\Http\Controllers\Api\RangoHorarioController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ReservaSlotController;

Route::apiResource('clientes', ClienteController::class);
Route::apiResource('profesionales', ProfesionalController::class);
Route::get('profesionales/{id}/disponibilidad', [DisponibilidadController::class, 'porProfesional']);
Route::post('profesionales/{id}/reservar-slot', [ReservaSlotController::class, 'reservar']);
Route::apiResource('reservas', ReservaController::class);
Route::post('reservas/cancelar-vencidas', [ReservaController::class, 'cancelarVencidas']);
Route::post('reservas/{id}/pagar', [ReservaController::class, 'pagar']);
Route::post('reservas/{id}/cancelar', [ReservaController::class, 'cancelar']);
Route::post('reservas/{id}/reprogramar', [ReservaController::class, 'reprogramar']);
Route::post('reservas/{id}/completar', [ReservaController::class, 'completar']);
Route::post('reservas/{id}/resena', [ReservaController::class, 'resena']);
Route::apiResource('servicios', ServicioController::class);
Route::apiResource('servicio-comun', ServicioComunController::class);
Route::apiResource('ubicaciones', UbicacionController::class);
Route::apiResource('reglas-disponibilidad', ReglaDisponibilidadController::class);
Route::apiResource('resenas', ResenaController::class);
Route::apiResource('usuarios', UsuarioController::class);
Route::apiResource('video-sesiones', VideoSesionController::class);
Route::apiResource('agendas', AgendaController::class);
Route::apiResource('horarios', HorarioController::class);
Route::apiResource('excepciones-disponibilidad', ExcepcionDisponibilidadController::class);
Route::apiResource('notificaciones', NotificacionController::class);
Route::apiResource('pagos', PagoController::class);
Route::post('paquete-servicios/{id}/comprar', [PaqueteCompradoController::class, 'comprar']);
Route::post('paquetes-comprados/{id}/pagar', [PaqueteCompradoController::class, 'pagar']);
Route::get('clientes/{id}/paquetes', [PaqueteCompradoController::class, 'porCliente']);
Route::apiResource('paquete-servicios', PaqueteServicioController::class);
Route::apiResource('ciclos', CicloController::class);
Route::apiResource('rangos-horarios', RangoHorarioController::class);
Route::post('/login', [AuthController::class, 'login']);
Route::middleware('auth:sanctum')->group(function () {
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::get('/me', [AuthController::class, 'me']);
});